/* Generated By:JavaCC: Do not edit this line. HTMLTokenConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HTMLTokenConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 1;
  /** RegularExpression Id. */
  int WHITESPACE = 2;
  /** RegularExpression Id. */
  int CLOSETAG = 3;
  /** RegularExpression Id. */
  int ANY = 4;
  /** RegularExpression Id. */
  int HTML = 5;
  /** RegularExpression Id. */
  int META = 6;
  /** RegularExpression Id. */
  int HTMLTAG = 7;
  /** RegularExpression Id. */
  int TABLE = 8;
  /** RegularExpression Id. */
  int LINK = 9;
  /** RegularExpression Id. */
  int SCRIPT = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int STYLE = 12;
  /** RegularExpression Id. */
  int BR = 13;
  /** RegularExpression Id. */
  int IMBEDDED = 14;
  /** RegularExpression Id. */
  int IMAGE = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int UNICODE = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WORD>",
    "<WHITESPACE>",
    "<CLOSETAG>",
    "<ANY>",
    "<HTML>",
    "<META>",
    "<HTMLTAG>",
    "<TABLE>",
    "<LINK>",
    "<SCRIPT>",
    "<DIV>",
    "<STYLE>",
    "<BR>",
    "<IMBEDDED>",
    "<IMAGE>",
    "<NUMBER>",
    "<UNICODE>",
  };

}
